<?php  //[STAMP] 88bb13027b5a7bb6ab61065b64df9abb
namespace ItalyStrap\Empress\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
