<?php

declare(strict_types=1);

namespace ItalyStrap\Empress;

use Auryn\InjectionException;
use Brick\VarExporter\ExportException;
use Brick\VarExporter\VarExporter;
use ItalyStrap\Config\ConfigInterface;
use Webimpress\SafeWriter\Exception\ExceptionInterface as FileWriterException;
use Webimpress\SafeWriter\FileWriter;

/**
 * @psalm-api
 */
class ProvidersCollection
{
    public const ENABLE_CACHE = 'config_cache_enabled';

    public const CACHE_FILEMODE = 'config_cache_filemode';

    private const CACHE_TEMPLATE = <<<'EOT'
<?php

declare(strict_types=1);

/**
 * This file generated by %s at %s
 */

%s
EOT;


    private ConfigInterface $config;
    private Injector $injector;

    /**
     * @param Injector $injector
     * @param ConfigInterface $config
     * @param iterable<class-string|callable> $providers
     * @param string|null $cachedConfigFile
     * @throws \ErrorException
     */
    public function __construct(
        Injector $injector,
        ConfigInterface $config,
        iterable $providers = [],
        ?string $cachedConfigFile = null
    ) {
        $this->injector = $injector;
        $this->config = $config;

        $collection = $this->loadCollectionFromProviders($providers);
        $this->config->merge(...$collection);
        $this->cacheConfig($cachedConfigFile);
    }

    /**
     * @return ConfigInterface
     */
    public function collection(): ConfigInterface
    {
        return $this->config;
    }

    /**
     * @param iterable<class-string|callable> $providers
     * @return array<array-key, mixed>
     * @throws \ErrorException
     */
    private function loadCollectionFromProviders(iterable $providers): array
    {
        $collection = [];
        foreach ($providers as $provider) {
            try {
                $result = $this->injector->execute($provider);
            } catch (InjectionException $e) {
                throw new \ErrorException(
                    \sprintf(
                        'An error occurred when executing %s: %s',
                        is_object($provider) ? get_class($provider) : gettype($provider),
                        $e->getMessage()
                    ),
                    0,
                    1,
                    __FILE__,
                    __LINE__,
                    $e
                );
            } catch (\Throwable $e) {
                throw new \ErrorException(
                    \sprintf(
                        'An error occurred when executing %s: %s',
                        is_object($provider) ? get_class($provider) : gettype($provider),
                        $e->getMessage()
                    ),
                    0,
                    1,
                    __FILE__,
                    __LINE__,
                    $e
                );
            }

            if ($result instanceof \Generator) {
                foreach ($result as $item) {
                    $collection[] = (array)$item;
                }
                continue;
            }

            $collection[] = (array)$result;
        }

        return $collection;
    }

    private function cacheConfig(?string $cachedConfigFile): void
    {
        if (null === $cachedConfigFile) {
            return;
        }

        if (!$this->config->get(static::ENABLE_CACHE, false)) {
            return;
        }

        try {
            $contents = sprintf(
                static::CACHE_TEMPLATE,
                static::class,
                date('c'),
                VarExporter::export(
                    $this->config->toArray(),
                    VarExporter::ADD_RETURN | VarExporter::CLOSURE_SNAPSHOT_USES
                )
            );
        } catch (ExportException $e) {
            throw new \ErrorException('Configuration cannot be cached', 0, 1, __FILE__, __LINE__, $e);
        }

        $this->writeCache($cachedConfigFile, $contents, $this->config->get(self::CACHE_FILEMODE, 0666));
    }

    private function writeCache(string $cachedConfigFile, string $contents, int $mode): void
    {
        try {
            FileWriter::writeFile($cachedConfigFile, $contents, $mode);
        } catch (FileWriterException $e) {
            // ignore errors writing cache file
        }
    }
}
