<?php

declare(strict_types=1);

namespace ItalyStrap\Empress;

use Brick\VarExporter\ExportException;
use Brick\VarExporter\VarExporter;
use ItalyStrap\Config\ConfigInterface;
use Safe\DateTimeImmutable;
use Webimpress\SafeWriter\Exception\ExceptionInterface as FileWriterException;
use Webimpress\SafeWriter\FileWriter;

final class ProvidersCache implements ProvidersCacheInterface
{
    private const CACHE_TEMPLATE = <<<'EOT'
<?php

declare(strict_types=1);

/**
 * This file generated by %s at %s
 */

%s
EOT;
    private ?string $file;

    public function __construct(?string $file = null)
    {
        $this->file = $file;
    }

    /**
     * @param ConfigInterface<array-key, mixed> $config
     */
    public function read(ConfigInterface $config): bool
    {

        $cachedConfigFile = $this->stringValue($config->get(self::CACHE_PATH, $this->file));

        if (
            $cachedConfigFile === ''
            || !file_exists($cachedConfigFile)
            || !is_file($cachedConfigFile)
            || !is_readable($cachedConfigFile)
        ) {
            return false;
        }

        $config->merge($this->loadCacheFile($cachedConfigFile));
        return true;
    }

    /**
     * @param ConfigInterface<array-key, mixed> $config
     */
    public function write(ConfigInterface $config): void
    {
        $cachedConfigFile = $this->stringValue($config->get(self::CACHE_PATH, $this->file));

        if ($cachedConfigFile === '') {
            return;
        }

        try {
            $contents = sprintf(
                self::CACHE_TEMPLATE,
                self::class,
                // Write an alternative to date('c')
                (new DateTimeImmutable('now'))->format('c'),
                VarExporter::export(
                    $config->toArray(),
                    VarExporter::ADD_RETURN | VarExporter::CLOSURE_SNAPSHOT_USES
                )
            );
        } catch (ExportException $e) {
            throw new \ErrorException('Configuration cannot be cached', 0, 1, __FILE__, __LINE__, $e);
        }

        $this->writeCache($cachedConfigFile, $contents, $this->intValue($config->get(self::CACHE_FILEMODE, 0666)));
    }

    private function writeCache(string $cachedConfigFile, string $contents, int $mode): void
    {
        try {
            FileWriter::writeFile($cachedConfigFile, $contents, $mode);
        } catch (FileWriterException $e) {
            throw new \ErrorException('Configuration cache cannot be written', 0, 1, __FILE__, __LINE__, $e);
        }
    }

    /**
     * @param mixed $value
     */
    private function stringValue($value): string
    {
        if ($value === null) {
            return '';
        }

        if (\is_scalar($value) || $value instanceof \Stringable) {
            return (string)$value;
        }

        throw new \ErrorException('Configuration cache path must be a string');
    }

    /**
     * @param mixed $value
     */
    private function intValue($value): int
    {
        if (\is_int($value)) {
            return $value;
        }

        if (\is_string($value) && \is_numeric($value)) {
            return (int)$value;
        }

        throw new \ErrorException('Configuration cache file mode must be an integer');
    }

    /**
     * @return array<array-key, mixed>
     */
    private function loadCacheFile(string $cachedConfigFile): array
    {
        try {
            $config = require $cachedConfigFile;
        } catch (\Throwable $e) {
            throw new \ErrorException('Configuration cache cannot be read', 0, 1, __FILE__, __LINE__, $e);
        }

        if (!\is_array($config)) {
            throw new \ErrorException('Configuration cache must return an array');
        }

        return $config;
    }
}
