name: Unit Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  tests:
    name: Test on PHP ${{ matrix.php }}

    runs-on: ubuntu-latest
    continue-on-error: ${{ contains('8.1,8.2,8.5', matrix.php) }}
    if: "!contains(github.event.head_commit.message, '--skip ci') && !github.event.pull_request.draft"

    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        dependencies:
          - "lowest"
          - "highest"
        include:
          - php: '8.5'
            composer-options: "--ignore-platform-reqs"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug2

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}

      - name: Run test suite
        run: vendor/bin/codecept run unit --coverage-text

#      - name: Run infection suite
#        run: vendor/bin/infection --threads=4

#      - name: Run PHPBench suite
#        run: vendor/bin/phpbench run --report=performance
